blank_issues_enabled: false
contact_links:
  - name: Official channels Proxmark3 Community
    url: https://github.com/RfidResearchGroup/proxmark3#official-channels
    about: Got questions? Ask in *official channels*, not in an issue
